[tool.poetry]
name = "django-with-poetry"
version = "0.1.0"
description = ""
authors = ["shawn <shawnfeng610@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
